apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-api
  namespace: cafeteria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafe-api
  template:
    metadata:
      labels:
        app: cafe-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: cafe-api
          image: cafe-api:latest   # tu imagen, cargada con minikube image load o en un registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
